" Vim Plugins
call plug#begin()

" Shorthand notation; fetches https://github.com/junegunn/vim-easy-align
Plug 'junegunn/vim-easy-align'

" Any valid git URL is allowed
Plug 'https://github.com/junegunn/vim-github-dashboard.git'

" Multiple Plug commands can be written in a single line using | separators
Plug 'honza/vim-snippets'
Plug 'hrsh7th/vim-vsnip'
Plug 'hrsh7th/vim-vsnip-integ'
Plug 'rafamadriz/friendly-snippets'

" On-demand loading
Plug 'preservim/nerdtree', { 'on': 'NERDTreeToggle' }

" Start NERDTree and put the cursor back in the other window.
autocmd VimEnter * NERDTree | wincmd p

Plug 'tpope/vim-fireplace', { 'for': 'clojure' }

" LSP config
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
Plug 'prabirshrestha/asyncomplete.vim'

" Colorschemes
Plug 'catppuccin/vim', { 'as': 'catppuccin' }
Plug 'jim-at-jibba/ariake-vim-colors'

" Plugin outside ~/.vim/plugged with post-update hook
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

call plug#end()


" Vim options
set number
set autoindent
set background=dark
set cursorline
syntax on
colorscheme quiet

set tabstop=2
set shiftwidth=2
set expandtab
set spell
set relativenumber
